"use client";
import {useMemo,useState} from "react";
import {useQuery} from "@tanstack/react-query";
import {CreditCard,Wallet,ArrowDownToLine,ArrowUpRight,Clock3,XCircle,RefreshCw,Search,ReceiptText} from "lucide-react";
import {Card,CardContent} from "../ui/card";
import {Button} from "../ui/button";
import {Badge} from "../ui/badge";
import {Input} from "../ui/input";
import {formatPrice,formatDate} from "../../lib/utils";
import {api} from "../../lib/api/client";
const sm:any={success:["Paid","border-emerald-200 bg-emerald-50 text-emerald-700"],paid:["Paid","border-emerald-200 bg-emerald-50 text-emerald-700"],pending:["Pending","border-amber-200 bg-amber-50 text-amber-700"],processing:["Processing","border-blue-200 bg-blue-50 text-blue-700"],failed:["Failed","border-red-200 bg-red-50 text-red-700"],refunded:["Refunded","border-purple-200 bg-purple-50 text-purple-700"],completed:["Completed","border-emerald-200 bg-emerald-50 text-emerald-700"]};
function Status({value}:{value:string}){const m=sm[value]||[value.replaceAll("_"," "),"border-slate-200 bg-slate-50 text-slate-700"];return <Badge variant="outline" className={m[1]}>{m[0]}</Badge>}
export default function PaymentDashboard({role}:{role:"customer"|"farmer"|"delivery"|"business"|"warehouse"}){
const [search,setSearch]=useState("");
const {data,isLoading,isError,refetch}=useQuery({queryKey:["payment-ledger",role],queryFn:()=>api.get("/payments/ledger/me",{params:{page:1,limit:100}})});
const {data:wd}=useQuery({queryKey:["payment-wallet"],queryFn:()=>api.get("/payments/wallet/info"),retry:false});
const {data:ww}=useQuery({queryKey:["payment-withdrawals"],queryFn:()=>api.get("/payments/wallet/withdrawals",{params:{page:1,limit:20}}),retry:false,enabled:role!=="customer"});
const rows=useMemo(()=>{const a=data?.data?.entries||data?.data?.ledger||data?.data||[];return (Array.isArray(a)?a:[]).map((x:any)=>({id:x.id||x._id||x.reference||String(Math.random()),amount:Number(x.amount)||0,direction:x.direction||"credit",status:(x.status||"completed").toLowerCase(),reference:x.reference||x.paymentId||x.orderId||"—",date:x.createdAt||x.date,description:x.description||x.metadata?.description||x.type||"Financial transaction"}))},[data]);
const rows2=rows.filter((x:any)=>(x.description+" "+x.reference).toLowerCase().includes(search.toLowerCase()));
const credits=rows.filter((x:any)=>x.direction==="credit").reduce((s:number,x:any)=>s+x.amount,0),debits=rows.filter((x:any)=>x.direction==="debit").reduce((s:number,x:any)=>s+x.amount,0);
const wallet=wd?.data||wd||{},withdrawals=ww?.data?.withdrawals||[];
const title=role==="customer"?"Payments & Wallet":role==="farmer"?"Payments & Settlements":role==="delivery"?"Earnings & Payouts":role==="business"?"Business Payments":"Warehouse Finance";
return <div className="space-y-6 p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center"><div className="flex-1"><h1 className="text-2xl font-semibold">{title}</h1><p className="text-sm text-slate-500">Track transactions, balances, refunds and settlements</p></div><Button variant="outline" size="sm" onClick={()=>refetch()}><RefreshCw className="mr-2 h-4 w-4"/>Refresh</Button></div>
<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Card><CardContent className="p-5"><span className="text-sm text-slate-500">Available balance</span><p className="mt-2 text-2xl font-bold">{formatPrice(Number(wallet.balance)||credits-debits)}</p></CardContent></Card><Card><CardContent className="p-5"><span className="text-sm text-slate-500">Money received</span><p className="mt-2 text-2xl font-bold text-emerald-700">{formatPrice(credits)}</p></CardContent></Card><Card><CardContent className="p-5"><span className="text-sm text-slate-500">Money paid</span><p className="mt-2 text-2xl font-bold">{formatPrice(debits)}</p></CardContent></Card><Card><CardContent className="p-5"><span className="text-sm text-slate-500">Transactions</span><p className="mt-2 text-2xl font-bold">{rows.length}</p></CardContent></Card></div>
<div className="grid gap-6 lg:grid-cols-[1fr_320px]"><Card><CardContent className="p-0"><div className="border-b p-5"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><Input className="pl-9" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search transaction, order or reference"/></div></div>{isLoading?<div className="p-12 text-center"><Clock3 className="mx-auto h-7 w-7 animate-pulse text-emerald-600"/></div>:isError?<div className="p-10 text-center"><XCircle className="mx-auto h-9 w-9 text-red-500"/><p className="mt-2">Payment history could not be loaded</p><Button className="mt-3" variant="outline" onClick={()=>refetch()}>Retry</Button></div>:rows2.length===0?<div className="p-10 text-center text-slate-500"><CreditCard className="mx-auto h-9 w-9"/><p className="mt-2">No transactions found</p></div>:<div className="divide-y">{rows2.map((x:any)=><div key={x.id} className="flex flex-col gap-3 p-5 hover:bg-slate-50 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3"><div className="rounded-xl bg-emerald-50 p-2.5"><CreditCard className="h-5 w-5 text-emerald-600"/></div><div><p className="font-semibold">{x.description}</p><p className="text-xs text-slate-500">Ref: {x.reference} · {x.date?formatDate(x.date):"—"}</p></div></div><div><p className={x.direction==="credit"?"font-bold text-emerald-700":"font-bold"}>{x.direction==="credit"?"+":"−"}{formatPrice(x.amount)}</p><Status value={x.status}/></div></div>)}</div>}</CardContent></Card>
<div className="space-y-4">{role!=="customer"&&<Card><CardContent className="p-5"><h2 className="font-semibold">Recent payouts</h2><p className="mt-1 text-sm text-slate-500">Withdrawal and settlement status</p><div className="mt-4 space-y-3">{withdrawals.length===0?<p className="text-sm text-slate-500">No payout requests yet.</p>:withdrawals.slice(0,5).map((w:any)=><div key={w.id||w._id} className="flex justify-between rounded-xl border p-3"><span className="font-medium">{formatPrice(Number(w.amount)||0)}</span><Status value={(w.status||"pending").toLowerCase()}/></div>)}</div></CardContent></Card>}{role==="customer"&&<Card><CardContent className="p-5"><h2 className="font-semibold">Payment safety</h2><p className="mt-2 text-sm text-slate-500">Online payments are verified server-side before an order is marked paid.</p><Button variant="outline" className="mt-4 w-full" onClick={()=>location.assign("/customer/refunds")}>View refunds</Button></CardContent></Card>}<Card><CardContent className="p-5"><h2 className="font-semibold">Payment lifecycle</h2><div className="mt-4 space-y-3 text-sm">{["Payment created","Gateway verification","Ledger entry","Settlement / refund"].map((s,i)=><div key={s} className="flex items-center gap-3"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-emerald-50 text-xs font-bold text-emerald-700">{i+1}</span>{s}</div>)}</div></CardContent></Card></div></div></div>}