"use client";
import {useQuery} from "@tanstack/react-query";
import {RefreshCw,CreditCard,CheckCircle2,Clock3,XCircle,IndianRupee} from "lucide-react";
import {Card,CardContent} from "../../components/ui/card";
import {Button} from "../../components/ui/button";
import {Badge} from "../../components/ui/badge";
import {formatPrice,formatDate} from "../../lib/utils";
import {api} from "../../lib/api/client";
const cls:any={success:"border-emerald-200 bg-emerald-50 text-emerald-700",pending:"border-amber-200 bg-amber-50 text-amber-700",failed:"border-red-200 bg-red-50 text-red-700",refunded:"border-purple-200 bg-purple-50 text-purple-700"};
export default function Page(){const {data:s,isLoading,isError,refetch}=useQuery({queryKey:["admin-payment-stats"],queryFn:()=>api.get("/payments/admin/stats")});const {data:l}=useQuery({queryKey:["admin-payment-list"],queryFn:()=>api.get("/payments/admin/list",{params:{page:1,limit:50}})});const x=s?.data||{};const rows=l?.data?.payments||[];return <div className="space-y-6 p-6"><div className="flex items-center"><div className="flex-1"><h1 className="text-2xl font-semibold">Payment Operations</h1><p className="text-sm text-slate-500">Monitor collections, failures, refunds and payment activity</p></div><Button variant="outline" size="sm" onClick={()=>refetch()}><RefreshCw className="mr-2 h-4 w-4"/>Refresh</Button></div>{isLoading?<div className="p-12 text-center"><Clock3 className="mx-auto animate-pulse"/></div>:isError?<Card><CardContent className="p-10 text-center"><XCircle className="mx-auto text-red-500"/><p>Payment statistics could not be loaded.</p></CardContent></Card>:<><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Card><CardContent className="p-5"><span className="text-sm text-slate-500">Total collected</span><p className="mt-2 text-2xl font-bold text-emerald-700">{formatPrice(x.totalAmount||0)}</p></CardContent></Card><Card><CardContent className="p-5"><span className="text-sm text-slate-500">Successful</span><p className="mt-2 text-2xl font-bold">{x.successfulPayments||0}</p></CardContent></Card><Card><CardContent className="p-5"><span className="text-sm text-slate-500">Failed</span><p className="mt-2 text-2xl font-bold text-red-600">{x.failedPayments||0}</p></CardContent></Card><Card><CardContent className="p-5"><span className="text-sm text-slate-500">Refunded</span><p className="mt-2 text-2xl font-bold text-purple-700">{formatPrice(x.totalRefunded||0)}</p></CardContent></Card></div><Card><CardContent className="p-0"><div className="border-b p-5"><h2 className="font-semibold">Recent transactions</h2><p className="text-sm text-slate-500">Gateway and order-level payment records</p></div><div className="divide-y">{rows.length===0?<div className="p-10 text-center text-slate-500">No payment records found.</div>:rows.map((p:any)=><div key={p.id} className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><div className="rounded-xl bg-slate-100 p-2.5"><CreditCard className="h-5 w-5"/></div><div><p className="font-semibold">{p.transactionId||p.id}</p><p className="text-xs text-slate-500">Order {p.orderId||"—"} · {p.paymentMethod||"—"} · {p.createdAt?formatDate(p.createdAt):"—"}</p></div></div><div className="text-left sm:text-right"><p className="font-bold">{formatPrice(Number(p.amount)||0)}</p><Badge variant="outline" className={cls[p.status]||"border-slate-200 bg-slate-50"}>{p.status}</Badge></div></div>)}</div></CardContent></Card></>}</div>}